### ISSUE TITLE
recon-ng marketplace module installation error

### ISSUE THREAD

**Issue by AnujK2901** [lanmaster53/recon-ng#108]
I am new to recon-ng and while currently installing modules, I am facing an issue for which I can not find any possible fix.
**Bug/Issue recreation steps:**

1. Running recon-ng from Kali terminal
2. executing marketplace refresh
3. then typing marketplace install all

Error I am facing:
`[recon-ng][default] > marketplace install all    
[*] Module installed: discovery/info_disclosure/cache_snoop    
[*] Module installed: discovery/info_disclosure/interesting_files
[*] Module installed: exploitation/injection/command_injector    
[*] Module installed: exploitation/injection/xpath_bruter
[*] Module installed: import/csv_file
[*] Module installed: import/list
[*] Module installed: import/masscan
[*] Module installed: import/nmap
[*] Module installed: recon/companies-contacts/bing_linkedin_cache
[*] Module installed: recon/companies-contacts/censys_email_address
[*] Module installed: recon/companies-contacts/pen
[*] Module installed: recon/companies-domains/censys_subdomains
[*] Module installed: recon/companies-domains/pen
[*] Module installed: recon/companies-domains/viewdns_reverse_whois
[*] Module installed: recon/companies-domains/whoxy_dns
[*] Module installed: recon/companies-hosts/censys_org
[*] Module installed: recon/companies-hosts/censys_tls_subjects
[*] Module installed: recon/companies-multi/github_miner
[*] Module installed: recon/companies-multi/shodan_org
[*] Module installed: recon/companies-multi/whois_miner
[*] Module installed: recon/contacts-contacts/abc
[*] Module installed: recon/contacts-contacts/mailtester
[*] Module installed: recon/contacts-contacts/mangle
[*] Module installed: recon/contacts-contacts/unmangle
[*] Module installed: recon/contacts-credentials/hibp_breach
[*] Module installed: recon/contacts-credentials/hibp_paste
[*] Module installed: recon/contacts-credentials/scylla
[*] Module installed: recon/contacts-domains/migrate_contacts
[*] Module installed: recon/contacts-profiles/fullcontact
[*] Module installed: recon/credentials-credentials/adobe
[*] Module installed: recon/credentials-credentials/bozocrack
[*] Module installed: recon/credentials-credentials/hashes_org
[*] Module installed: recon/domains-companies/censys_companies
[*] Module installed: recon/domains-companies/pen
[!] Module installation failed: recon/domains-companies/whoxy_whois.
[!] Invalid response from module repository (404).`

I have tried following:

- restarting
- updating using `apt-get update && apt-get upgrade`
- logging as root user
- searching on internet

**Comment by jasonmull** [comment]
I'm also seeing this error at the same place.  v5.1.1

**Comment by 0xGh0st** [comment]
Yes the error exists due to the modules.yml file in recon-ng-marketplace:
line 383: last_updated: '2020-06-17'
  name: Whoxy Whois Lookup
  path: recon/domains-companies/whoxy_whois
but in the modules on that repo you have: whoxy_companies.py, I believe there is an issue in how the url is being resolved, the naming convention is incorrect.

**Comment by TheTechromancer** [comment]
I believe the true issue here is that an error in the installation of a single module cancels the entire process for all modules.

**Comment by leebaird** [comment]
I confirm the same errors and versions as well.

**Comment by AnujK2901** [comment]
> I believe the true issue here is that an error in the installation of a single module cancels the entire process for all modules.

Yes. It seems like this module has been removed and while installing this module, this failure terminates the overall process to complete installation of all remaining modules.

**Comment by AnujK2901** [comment]
From my point of view, there are two things for the developers contributing this project.

- Removing/Fixing `whoxy_whois`
- Giving us an argument or something as well to continue installing rest modules without stopping for similar events in near future.

**Comment by lanmaster53** [comment]
This should be fixed now, but I agree that it should be handled more gracefully. Thank you for reporting and for your recommendations.

**Comment by jayakrishnanvkm** [comment]
try to install modules one by one as many of them need api keys.

keys add github <your api key>

and then install github module

**Comment by rawr-droid** [comment]
Type the Cat etc/nsswitch.conf and look for hosts line and the value should be files DNS, if there's anything that comes between the files DNS words, delete it with a text editor and save it.Hope this helps

**Comment by julietasafa** [comment]
I have a problem. When i try to install the modules: marketplace install example... the answer is: No such file or directory. This mensage apear in all attempts to install diferent modules. I triyed to use AI to solve this, but yhe problem persist.

**Comment by LMGTonka** [comment]
> I have a problem. When i try to install the modules: marketplace install example... the answer is: No such file or directory. This mensage apear in all attempts to install diferent modules. I triyed to use AI to solve this, but yhe problem persist.

I am having the same issue, when attempting to install all it responds with

no such file or directory for cache_snoop.py
