### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by jwallaceni** [lanmaster53/recon-ng#169]
404 not found.

**Comment by lucienvanlinden** [comment]
I have the same issue; Analytics dump below;

[recon-ng][default] > modules load recon/profiles-profiles/profiler
[*] Analytics disabled.
[recon-ng][default][profiler] > run
[*] No validator required.
[*] DATABASE => /home/kali/.recon-ng/workspaces/default/data.db
[*] QUERY => INSERT OR REPLACE INTO dashboard (module, runs) VALUES ('recon/profiles-profiles/profiler', COALESCE((SELECT runs FROM dashboard WHERE module='recon/profiles-profiles/profiler')+1, 1))
[*] Retrieving https://raw.githubusercontent.com/WebBreacher/WhatsMyName/master/web_accounts_list.json...
[*] ========================= REQUEST =========================
url:    https://raw.githubusercontent.com/WebBreacher/WhatsMyName/master/web_accounts_list.json
method: GET /WebBreacher/WhatsMyName/master/web_accounts_list.json
header: User-Agent: Recon-ng/v5
header: Accept-Encoding: gzip, deflate, br
header: Accept: */*
header: Connection: keep-alive
[*] ========================= RESPONSE =========================
status: 404 Not Found
header: Connection: keep-alive
header: Content-Length: 14
header: Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
header: Strict-Transport-Security: max-age=31536000
header: X-Content-Type-Options: nosniff
header: X-Frame-Options: deny
header: X-XSS-Protection: 1; mode=block
header: Content-Type: text/plain; charset=utf-8
header: X-GitHub-Request-Id: 0931:CC30:17213D:1877D1:634FD537
header: Accept-Ranges: bytes
header: Date: Wed, 19 Oct 2022 10:45:11 GMT
header: Via: 1.1 varnish
header: X-Served-By: cache-ams21073-AMS
header: X-Cache: MISS
header: X-Cache-Hits: 0
header: X-Timer: S1666176312.516061,VS0,VE176
header: Vary: Authorization,Accept-Encoding,Origin
header: Access-Control-Allow-Origin: *
header: X-Fastly-Request-ID: d9c117ffe31d1d36ba0141a521043f742aa3abe4
header: Expires: Wed, 19 Oct 2022 10:50:11 GMT
header: Source-Age: 0
body:   b'404: Not Found'
Looking Up Data For: Lucien

**Comment by gbinv** [comment]
Fixed by https://github.com/lanmaster53/recon-ng-marketplace/pull/230

**Comment by TheGentleman22** [comment]
> Fixed by [lanmaster53/recon-ng-marketplace#230](https://github.com/lanmaster53/recon-ng-marketplace/pull/230)

How do we install this fix? I have tried marketplace refresh, apt update, ive also tried uninstalling and reinstalling the module. from recon-ng, finally ive tried uninstalling and reinnstallng recon-ng from the repo, with still no luck. I have also tried grabbing a copy of recon-ng with git clone however this doesn't fix the error either.

**Comment by gbinv** [comment]
> > Fixed by [lanmaster53/recon-ng-marketplace#230](https://github.com/lanmaster53/recon-ng-marketplace/pull/230)
> 
> How do we install this fix? I have tried marketplace refresh, apt update, i've also tried uninstalling and reinstalling the module from recon-ng. I've also tried uninstalling and reinstallng recon-ng from the repo, with still no luck. I have also tried grabbing a copy of recon-ng with git clone however this doesn't fix the error either.

replace the existing "profiler.py" module with this one: https://github.com/gbinv/recon-ng-marketplace/blob/profiler_fix/modules/recon/profiles-profiles/profiler.py
